webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.lambdatest.LambdaTestSerenityDriver

# Disables the internal Serenity visibility checks that cause the JS error
serenity.native.events = false
serenity.use.native.events = false

# Global timeouts
webdriver.timeouts.implicitlywait = 15000
webdriver.wait.for.timeout = 15000

serenity.project.name = LambdaTest Serenity Java 25
serenity.take.screenshots = FOR_FAILURES